### ISSUE TITLE
Task 01 -- Create GitHub account and fork two repositories

### ISSUE THREAD

**Issue by dudung** [dudung/fi6004-01-2022-2#1]
+ To access [GitHub](https://github.com) please [create account](https://github.com/signup) or [login](https://github.com/login).
+ To participate [py-jupyter-nb](https://github.com/dudung/py-jupyter-nb) repository please [fork](https://github.com/dudung/py-jupyter-nb/fork).
+ To participate [fi6004-01-2022-2](https://github.com/dudung/fi6004-01-2022-2) repository plese [fork](https://github.com/dudung/fi6004-01-2022-2/fork).

Report  your GitHub user link by repying to this message, e.g
> https://github.com/dudung

This assignment is valid until 1 Feb 2023, 09.00 GMT+07.

**Comment by NurAnnisa-NA23** [comment]
Nur Annisa (20222014)
https://github.com/NurAnnisa-NA23

**Comment by andim53** [comment]
Andi Muhammad Nur Fitrah Syamsul 
20222013
https://github.com/andim53/

**Comment by mrisyadn** [comment]
Muhammad Risyad Naufal (20222009)
https://github.com/muhammadrisyadnaufal

**Comment by lattov** [comment]
https://github.com/lattov

**Comment by syifahts** [comment]
https://github.com/syifahts

**Comment by benyagustirandi** [comment]
Beny Agustirandi (20222017)
https://github.com/benyagustirandi

**Comment by denrmdani** [comment]
Deni Ramdani (20222011)
https://github.com/denrmdani

**Comment by raihanmr1211** [comment]
Raihan Mohammad Rahman (20222003)
https://github.com/raihanmr1211

**Comment by dudung** [comment]
+ Terima kasih, @NurAnnisa-NA23, @andim53, @muhammadrisyadnaufal, @lattov, @syifahts, @benyagustirandi, @denrmdani, @raihanmr1211.
+ Task 01 ditutup.

**Comment by dudung** [comment]
@lattov, @syifahts, @denrmdani, dan @andim53, tolong slide dan paper-like dalam format PDF diunggah ke https://github.com/dudung/fi6004-01-2022-2/issues/9 sebelum jam 13 hari ini, Rabu, 6 Juni 2023, ya. Terima kasih
