### ISSUE TITLE
Task 02 -- Review materials and exercises

### ISSUE THREAD

**Issue by dudung** [dudung/fi6004-01-2022-2#2]
+ Kerjakan tugas dalam berkas PDF berikut [task_02.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10738343/task_02.pdf)
+ Unggah jawaban di sini dan juga di [Edunex 155366](https://edunex.itb.ac.id/courses/45279/preview/155366)

**Comment by lattov** [comment]
Maaf, Pak saya belum masuk ke EDUNEX.

Nama: Alwali Walyatalattov Solichin
NIM: 20221305

**Comment by dudung** [comment]
Silakan, @lattov. Tokennya `BRMH5A`. Terima kasih.

**Comment by lattov** [comment]
Terima kasih, Pak. Sudah bisa akses EDUNEX. Terkait perpindahan jadwalnya, bagaimana ya Pak?
Tadi sudah berdiskusi dengan teman-teman untuk Kamis jam 11-13 apakah bisa Pak @dudung ? Terima kasih

**Comment by dudung** [comment]
Terima kasih, @lattov. Apakah ada alternatif lainnya?

**Comment by mrisyadn** [comment]
Assalamualaikum WR. WB. Pak, selamat siang. 

Berikut saya lampirkan jawaban dari tugas02 untuk mata kuliah Pengolahan Data Sistem Fisis

Terima kasih Pak

[Muhammad Risyad Naufal_20222009_Tugas02.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10791092/Muhammad.Risyad.Naufal_20222009_Tugas02.pdf)

**Comment by andim53** [comment]
Assalamualaikum WR. WB. 

Berikut jawaban dari tugas02 untuk mata kuliah Pengolahan Data Sistem Fisis.

Terimakasih.

[Andi Muhammad Nur Fitrah Syamsul_20222013_task02.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10791404/Andi.Muhammad.Nur.Fitrah.Syamsul_20222013_task02.pdf)

**Comment by lattov** [comment]
Assalamualaikum wr.wb

Berikut saya lampirkan jawaban dari tugas_02 mata kuliah Pengolahan Data Sistem Fisis.

Terima kasih, Pak
[Tugas 2_Alwali Walyatalattov Solichin_20221305.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10792225/Tugas.2_Alwali.Walyatalattov.Solichin_20221305.pdf)

**Comment by benyagustirandi** [comment]
Assalamualaikum pak, Berikut saya lampirkan jawaban tugas_02 Pengolahan Data Sistem Fisis (FI6004)
Terimakasih pak.

[Beny Agustirandi_20222017_Tugas Pengolahan Data Sistem Fisis.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10794842/Beny.Agustirandi_20222017_Tugas.Pengolahan.Data.Sistem.Fisis.pdf)

**Comment by syifahts** [comment]
Assalamu'alaikum, pak. Berikut saya lampirkan tugas 2 Pengolahan Data Sistem Fisis (FI6004).

Terimakasih.
[Syifa Hilya Tsaniya - 20222001.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10795486/Syifa.Hilya.Tsaniya.-.20222001.pdf)

**Comment by denrmdani** [comment]
Assalamualaikum, Pak. Berikut saya lampirkan tugas 2 Pengolahan Data Sistem Fisis. Terima kasih.

[20222011_Deni Ramdani_task_02.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10798885/20222011_Deni.Ramdani_task_02.pdf)

**Comment by NurAnnisa-NA23** [comment]
Assalamu'alaikum, Pak. Berikut saya lampirkan laporan tugas 2 Pengolahan Data Sistem Fisis. Terima kasih Pak.

[Task_02_20222014_Nur Annnisa_Pengolahan Data Sistem Fisis.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10799237/Task_02_20222014_Nur.Annnisa_Pengolahan.Data.Sistem.Fisis.pdf)

Bapak maaf, saya Nur Annisa 20222014 juga belum masuk edunex karena PRS.

**Comment by raihanmr1211** [comment]
Selamat pagi Pak. Berikut saya lampirkan laporan tugas 2 Pengolahan Data Sistem Fisis. Terima kasih Pak.
[20222003_Raihan Mohammad Rahman_Task_02.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10799321/20222003_Raihan.Mohammad.Rahman_Task_02.pdf)
Mohon maaf Pak, saya belum masuk edunex karena baru PRS. Terima kasih

**Comment by dudung** [comment]
+ Terima kasih, @muhammadrisyadnaufal, @andim53, @lattov, @benyagustirandi, @syifahts, @denrmdani, @NurAnnisa-NA23, @raihanmr1211.
+ Task 02 ditutup.
