### ISSUE TITLE
Jadwal kuliah setelah 15 Februari 2023

### ISSUE THREAD

**Issue by dudung** [dudung/fi6004-01-2022-2#3]
Terima kasih, Pak. Sudah bisa akses EDUNEX. Terkait perpindahan jadwalnya, bagaimana ya Pak?
Tadi sudah berdiskusi dengan teman-teman untuk Kamis jam 11-13 apakah bisa Pak @dudung ? Terima kasih

_Originally posted by @lattov in https://github.com/dudung/fi6004-01-2022-2/issues/2#issuecomment-1431395836_

**Comment by dudung** [comment]
+ Terima kasih, @lattov.
+ Apakah dapat ada beberapa alternatif waktu sehingga memudahkan?
+ Tolong dijawab di sini, ya. Hal ini agar terpisah issuenya karena yang sebelumnya untuk tugas 2. Terima kasih

**Comment by lattov** [comment]
Mohon maaf, Pak **@dudung** saya baru sempat mengabarkan.

Alternatif waktunya dari rekan-rekan jika memungkinkan adalah Selasa Jam 14.00.
Terima kasih, Pak

**Comment by dudung** [comment]
Jadi yang dapat dihadiri Rekan-rekan adalah:
- Selasa, 14-16
- Rabu, 09-11 (jadwal saat ini)
- Kamis, 11-13

Saya akan sampaikan ke Pak Freddy Haryanto, Pak Nurhasan, dan Pak Suprijadi. Terima kasih, @lattov.

**Comment by mrisyadn** [comment]
Assalamualaikum pak, selamat siang. Untuk kelanjutan jadwal kuliah Pengolahan Data Sistem Fisis bagaimana ya pak? Terima kasih 🙏

**Comment by dudung** [comment]
+ Waalaikumsalam wr wb, @muhammadrisyadnaufal. Terima kasih telah menyakan.
+ Perkuliahan menjadi **Kamis, 11-13** di **1203** dengan pengajar **Pak Freddy Haryanto** untuk **22 Feb 2023**.
+ Informasi kuliah berikutnya akan disampaikan oleh Beliau atau di sini.
+ Terima kasih.

**Comment by mrisyadn** [comment]
Baik Pak @dudung , Terima kasih banyak atas infonya pak

**Comment by lattov** [comment]
Assalamualaikum, selamat siang Pak Dudung mau bertanya.

Kelas bersama Pak Suprijadi apakah kembali ke hari Rabu seperti jadwal original atau tetap di hari Kamis jam 11-13 ya Pak? Terima kasih Pak

Wassalamualaikum

**Comment by dudung** [comment]
+ Seingat saya masih Pak Nurhasan satu kali lagi, @lattov. Saya konfirmasi dulu. Terima kasih.
+ Hari untuk pertemuan dengan Pak Suprijadi juga akan saya tanyakan.

**Comment by dudung** [comment]
+ Jadwal Pak Suprijadi adalah Rabu, 0900-1100
+ Pak Nurhasan belum konfirmasi untuk Kamis minggu ini.

**Comment by lattov** [comment]
Baik, Pak terima kasih. Berarti kami menunggu informasi dari Pak Nurhasan terlebih dahulu ya Pak?

**Comment by dudung** [comment]
Rencananya Pak Suprijadi masuk hari ini jam 09-11 di 1202. Tolong disampaikan ke rekan-rekan ya, @lattov. Terima kasih.

**Comment by lattov** [comment]
Baik siap, Pak @dudung. Terima kasih atas informasinya

**Comment by dudung** [comment]
+ Selamat pagi, @lattov.
+ Slide harap diunggah ke [Edunex](https://edunex.itb.ac.id/courses/45279/preview/164869/71501) dan di #5.
+ Tolong disampaikan ke Rekan-rekan yang lainnya. Batasnya nanti malam, sehingga dapat setelah kuliah.
+ Terima kasih.

**Comment by dudung** [comment]
+ Bila perlu diskusi, dapat [membuat issue baru](https://github.com/dudung/fi6004-01-2022-2/issues/new/choose).
+ Issue ini ditutup karena telah berisi informasi yang tidak sesuai lagi dengan judulnya.
+ Terima kasih.
