### ISSUE TITLE
Exam 01 -- Ujian Tengah Semester (praktek, bagian take-home)

### ISSUE THREAD

**Issue by dudung** [dudung/fi6004-01-2022-2#4]
- Buat repository di akun Anda, e.g. `jawaban-uts`.
- Sampaikan hasil jawaban Anda (take-home) dalam bentuk berkas `202XXYY.ipynb`, dengan `202XXYY` adalah NIM Anda.
- Tuliskan tautan ke berkas jawaban (take-home) tersebut di sini dan di [Edunex](https://edunex.itb.ac.id/courses/45279/preview/160298/68902).
- [Soal UTS.pdf](https://github.com/dudung/fi6004-01-2022-2/files/10927903/Soal.UTS.pdf)

**Comment by andim53** [comment]
Andi Muhammad Nur Fitrah Syamsul
20222013
[Tautan](https://github.com/andim53/jawaban-uts.git)

**Comment by denrmdani** [comment]
Berikut jawaban UTS Deni Ramdani-20222011.
[20222011.ipynb](https://github.com/denrmdani/jawaban-uts/blob/main/20222011.ipynb)

**Comment by benyagustirandi** [comment]
Assalamualaikum pak, berikut jawaban UTS Beny Agustirandi (20222017)
https://github.com/benyagustirandi/jawaban-uts

**Comment by mrisyadn** [comment]
Assalamualaikum pak, berikut jawaban UTS Muhammad Risyad Naufal-20222009
https://github.com/muhammadrisyadnaufal/jawaban-uts
Terima kasih pak

**Comment by lattov** [comment]
Assalamualaikum Pak, berikut jawaban UTS saya , mohon maaf jika masih banyak kekurangan.
Terima kasih, Pak

[https://github.com/lattov/jawaban-uts](url)

**Comment by syifahts** [comment]
Assalamu'alaikum pak. Berikut jawaban UTS saya. Terimakasih banyak pak

[UTS FI6004 - Syifa Hilya Tsaniya (20222001)](https://github.com/syifahts/Mid-Term-Test---FI6004-Physical-Data-Processing)

**Comment by NurAnnisa-NA23** [comment]
Assalamu'alaikum Pak. Berikut jawaban UTS Nur Annisa 20222014. Terima kasih Pak.
https://github.com/NurAnnisa-NA23/Jawaban-UTS.git

**Comment by raihanmr1211** [comment]
Assalamu'alaikum Pak. Berikut jawaban UTS saya Raihan Mohammad Rahman NIM 20222003. Terima kasih Pak.
https://github.com/raihanmr1211/jawaban-uts

**Comment by dudung** [comment]
+ Terima kasih, @andim53, @denrmdani, @benyagustirandi, @muhammadrisyadnaufal, @lattov, @syifahts, @NurAnnisa-NA23, @raihanmr1211.
+ Exam 01 ditutup.
