### ISSUE TITLE
Task 03 -- Slide presentasi usulan topik RBL

### ISSUE THREAD

**Issue by dudung** [dudung/fi6004-01-2022-2#5]
+ Perhatikan kembali ketentuan slide yang telah diberikan di [GitHub](https://github.com/dudung/fi6004-01-2022-2/blob/main/note/10/20230329-0.jpeg).
+ Simpan dalam format PDF dan sampaikan di sini.
+ Unggah juga berkasnya ke [Edunex](https://edunex.itb.ac.id/courses/45279/preview/164869/71501).

**Comment by andim53** [comment]
[Andi Muhammad Nur Fitrah Syamsul 20222013.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11155116/Andi.Muhammad.Nur.Fitrah.Syamsul.20222013.pdf)

Andi Muhammad Nur Fitrah Syamsul 
20222013

**Comment by benyagustirandi** [comment]
[20222017_Beny Agustirandi_RBL.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11155126/20222017_Beny.Agustirandi_RBL.pdf)

Assalamualaikum pak, berikut PPT rencana RBL saya

Beny Agustirandi
20222017

**Comment by mrisyadn** [comment]
Assalamualaikum Pak. Berikut saya lampirkan PPT rencana RBL saya
Muhammad Risyad Naufal
20222009
Terimakasih

[RBL Pengolahan Data Sistem Fisis - Muhammad Risyad Naufal - 20222009.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11155139/RBL.Pengolahan.Data.Sistem.Fisis.-.Muhammad.Risyad.Naufal.-.20222009.pdf)

**Comment by denrmdani** [comment]
Assalamualaikum, berikut ini slide usulan topik RBL saya:
Deni Ramdani
20222011

[20222011_Deni Ramdani-Topik RBL.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11156030/20222011_Deni.Ramdani-Topik.RBL.pdf)

**Comment by NurAnnisa-NA23** [comment]
Assalamu'alaikum Pak, berikut ini file presentasi usulan topik RBL saya,
Nur Annisa 20222014
Terima kasih Pak.
[RBL Pengolahan Data Sistem Fisis_Nur Annisa_20222014.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11157954/RBL.Pengolahan.Data.Sistem.Fisis_Nur.Annisa_20222014.pdf)

**Comment by lattov** [comment]
Assalamualaikum selamat malam, Pak.
Berikut saya lampirkan presentasi RBL saya, terima kasih.


[20221305-Alwali Walyatalattov Solichin.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11159009/20221305-Alwali.Walyatalattov.Solichin.pdf)

**Comment by raihanmr1211** [comment]
Selamat malam Pak. Berikut saya lampirkan presentasi RBL saya, terima kasih.
[20222003-Raihan Mohammad Rahman.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11160709/20222003-Raihan.Mohammad.Rahman.pdf)

**Comment by syifahts** [comment]
[Syifa Hilya Tsaniya.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11202148/Syifa.Hilya.Tsaniya.pdf)

mohon maaf atas keterlambatannya pak, berikut saya lampirkan file presentasi rbl (sudah saya upload di edunex minggu lalu)

**Comment by dudung** [comment]
Tugas 03 ini ditutup. Terima kasih @andim53, @benyagustirandi, @muhammadrisyadnaufal, @denrmdani, @NurAnnisa-NA23, @lattov, @raihanmr1211, dan @syifahts.
