### ISSUE TITLE
Laporan dan slide RBL

### ISSUE THREAD

**Issue by dudung** [dudung/fi6004-01-2022-2#9]
+ Laporan dan slide RBL diunggah di sini dalam bentuk PDF.
+ Batasnya adalah, Selasa, 6 Juni 2023, jam 1300.
+ Bila memerlukan perpanjangan waktu, harap memberitahukan terlebih dahulu.

**Comment by benyagustirandi** [comment]
Assalamualaikum pak, berikut laporan draft paper dan slide RBL kami atas nama
1. Beny Agustirandi (20222017)
2. Raihan M. Rahman (20222003)

[Draft Paper Pengolahan Data Sistem Fisis English .pdf](https://github.com/dudung/fi6004-01-2022-2/files/11652837/Draft.Paper.Pengolahan.Data.Sistem.Fisis.English.pdf)

[RBL Pengolahan Data Sistem Fisis.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11652843/RBL.Pengolahan.Data.Sistem.Fisis.pdf)


Untuk Revisi sudah kami lakukan, tambahan di Introduction draft paper untuk menentukan benchmark dengan pengujian pergeseran piksel dari dua buah gambar dengan objek yang berpindah, dan pergeseran piksel dari tiga buah gambar dengan posisi objek tetap namun ukuran objek berubah. Hasil dari pengolahan benchmark ditampilkan di PPT slide ke 3 dan slide ke 4.

Terimakasih pak

**Comment by mrisyadn** [comment]
Assalamualaikum WR. WB.  Pak.
Berikut kami lampirkan laporan dalam bentuk draft paper dan slide PPT RBL kami atas nama
1. Muhammad Risyad Naufal (2022009)
2. Nur Annisa (20222014)


[Muhammad Risyad Naufal (20222010)_Nur Annisa (20222014)_Paper RBL Pengolahan Data Sistem Fisis_Magnetotelurik.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11653889/Muhammad.Risyad.Naufal.20222010._Nur.Annisa.20222014._Paper.RBL.Pengolahan.Data.Sistem.Fisis_Magnetotelurik.pdf)
[Muhammad Risyad Naufal (20222009)_Nur Annisa (20222014)_PPT RBL Pengolahan Data Sistem Fisis_Magnetotelurik.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11653890/Muhammad.Risyad.Naufal.20222009._Nur.Annisa.20222014._PPT.RBL.Pengolahan.Data.Sistem.Fisis_Magnetotelurik.pdf)

Terima kasih Pak

**Comment by syifahts** [comment]
Selamat pagi pak, berikut saya lampirkan laporan RBL, draft paper dan slide ppt atas nama:

Deni Ramdani (20222011)
Syifa Hilya Tsaniya (20222001)
[PPT Pengolahan Data Sistem Fisis 2023-06-06 02_18_52.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11659305/PPT.Pengolahan.Data.Sistem.Fisis.2023-06-06.02_18_52.pdf)
[Paper Pengolahan Data Sistem Fisis 2023-06-06 02_19_09.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11659308/Paper.Pengolahan.Data.Sistem.Fisis.2023-06-06.02_19_09.pdf)

**Comment by lattov** [comment]
Assalamualaikum, wr.wb
Selamat pagi, Pak Dudung. Berikut saya lampirkan laporan RBL serta presentasi nya dalam format .pdf
Mohon maaf jika masih ada kekurangan. Terimakasih, Pak

Alwali Walyatalattov Solichin (20221305)
Andi Muhammad Nur Fitrah Syamsul (20222013)

[RBL Pengolahan Data Sistem Fisis Presentation.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11659614/RBL.Pengolahan.Data.Sistem.Fisis.Presentation.pdf)

[RBL Pengolahan Data Sistem Fisis.pdf](https://github.com/dudung/fi6004-01-2022-2/files/11659617/RBL.Pengolahan.Data.Sistem.Fisis.pdf)

**Comment by dudung** [comment]
Terima kasih, @benyagustirandi, @muhammadrisyadnaufal, @syifahts, dan @lattov.
